feat: added BuildConfigurationPage, BuildTypeElement, BuildTypePage, CreateBuildTypePage, CreateBuildTypeTest, and @BeforeMethod in BaseUiTest for autotests
belousovanya/teamcity-testing-framework pull request #18
Opened 2024-11-04 20:23 UTC by belousovanya

• BuildTypeElement, BuildConfigurationPage, BuildTypePage, и CreateBuildTypePage  - классы страниц и элементов UI для работы с созданием конфигураций сборок.
• Реализован тест CreateBuildTypeTest, содержащий два сценария:
      •	Позитивный сценарий userCreatesBuildType, который проверяет успешное создание BuildType с валидным именем.
      •Негативный сценарий userCannotCreateBuildTypeWithoutName, который проверяет, что невозможно создать BuildType без имени.
       •Добавлена настройка TestDataStorage.

2024-11-10 21:32 UTC, nobugs-me requested changes
Привет! 

Спасибо за выполнение базового ДЗ! ⚡️

Тест выполнен корректно, но не хватает проверки, что сущность не создалась в негативном тесте. 

Добавь, пожалуйста, и будет Approve 🤝

2024-11-10 21:32 UTC, nobugs-me commented on src/test/java/com/example/teamcity/ui/CreateBuildTypeTest.java
> +    }
Также нужно добавить проверку, что на уровне API сущность не создалась.

2024-11-13 06:24 UTC, belousovanya commented on src/test/java/com/example/teamcity/ui/CreateBuildTypeTest.java
> +    }
@nobugs-me, исправила

2024-11-13 12:49 UTC, nobugs-me commented on src/test/java/com/example/teamcity/ui/CreateBuildTypeTest.java
> +    }
Спасибо!

2024-11-24 13:13 UTC, merged